### ISSUE TITLE
Correlation score

### ISSUE THREAD

**Issue by jessakay** [koszullab/chromosight#26]
Thank you for making available this great tool! I've been trying to apply the `quantify` module for scoring interaction strength at pairs of transcription factor binding sites using the supplied loop kernel, but the scores are all strictly positive unlike what's been shown for Rad21 in the tutorial or your manuscript.

Could you please help me troubleshoot what I'm doing wrong? I used the following command on the files [here](https://drive.google.com/open?id=1SRSPbFAFj7X0Y733dpa4ceTYZZh3MNAW)

`chromosight quantify --pattern loops sites.bed2d 5000.cool out`

**Comment by cmdoret** [comment]
Hi @jessakay, 

Thanks for raising an issue, there was indeed a regression preventing negative scores in quantify. I have just released version 1.0.0 which fixes this among other issues. 

I ran `chromosight quantify` with the new version on your data and it seems to work fine, negative coefficients are back as it should be ! 

You can upgrade to the new version using `pip install --upgrade chromosight`, tell me if everything works for you

**Comment by AxelBreuer** [comment]
Quel service après vente ! Bravo !

**Comment by jessakay** [comment]
Et ça marche! Merci beaucoup
