### ISSUE TITLE
output file name

### ISSUE THREAD

**Issue by Phlya** [koszullab/chromosight#27]
Hello,

I am trying to use `chromosight detect` in a snakemake pipeline, and I have a problem that there is no way to change the default output file name. I could create a new folder for each analysis, and maybe automatically move/rename the files, but that's not the most convenient approach... Is there a reason why it's impossible to customize the file names? (or file prefix, since `chromosight detect` always saves at least two files)

Thanks!
Ilya

**Comment by cmdoret** [comment]
Hi @Phlya ,

Yes, I could add like a `--prefix` option. In a snakemake workflow, the output filenames would currently be:
```
output:
    tbl = "{sample}/loops_out.txt",
    win = "{sample}/loops_out.json"
```
whereas with a `--prefix` option, it would become:
```
output:
    tbl = "{sample}.txt",
    win = "{sample}.json"
````

Do you think the latter option would be more convenient to work with ?
In that case the command
`chromosight detect sample.cool sample/`
would become
`chromosight detect --prefix sample sample.cool`

I agree the possibility to customize output filenames would be nice. I'm just a bit concerned the CLI is becoming bloated with all the options. What do you think about a `--prefix` option ?

**Comment by Phlya** [comment]
Prefix is good! Assuming it allows to include a path to a different folder, and it's not just saved in the same folder with the prefix...

**Comment by cmdoret** [comment]
Right, it would be confusing to add `--prefix` while keeping a positional argument for the output directory, I think I'll simply replace the output directory argument by output prefix and remove predefined output filenames. This way, `chromosight detect input.cool out_dir/output` would produce `out_dir/output.txt` and `out_dir/output.json`. That seems more intuitive.

Thanks for the feedback, I'll get back to you. !

**Comment by Phlya** [comment]
Nice, sounds good. Just important for it to handle absolute and relative paths. Thank you!

**Comment by cmdoret** [comment]
Hi, this has been addressed in #28, I'll make a release soon when checks have passed :)

**Comment by cmdoret** [comment]
This is now the default behaviour in chromosight 1.2.0, thanks !

**Comment by Phlya** [comment]
Awesome, thanks!

**Comment by Phlya** [comment]
Very quick fix!
