### ISSUE TITLE
Adding of quantification of pattern

### ISSUE THREAD

**Issue by axelcournac** [koszullab/chromosight#3]
On the to do list (an easy one!)
- add the quantification of a set of positions to a specific generic pattern: will allow for example to quantify between 2 biological conditions it a set of genomic positions do more loops than another one, could be interesting for many of our projects.
Could be implemented by taking the mean of the correlation coefficients of detector function.

**Comment by cmdoret** [comment]
Added through the `quantify` subcommand as of chromosight 0.2.0
