### ISSUE TITLE
call peaks between different chromosomes

### ISSUE THREAD

**Issue by jazberna1** [koszullab/chromosight#36]
Hello Chromosight developers,

This is not an issue. It's just I would like to know if Chromosight  is able to call peaks between different chromosomes.

Thanks so much
Jorge

**Comment by cmdoret** [comment]
Hi @jazberna1,

Yes, it is possible but it will take up more RAM. You just need to provide the `--inter` option.

Best,
Cyril

**Comment by cmdoret** [comment]
Sorry, there was actually a bug in the `--inter` option that went unnoticed. I just fixed it and made a new release (1.4.0), which is available via pip and will be available via conda in a few hours.

**Comment by jazberna1** [comment]
Hello Cyril,

Thanks so much for the fix!

Jorge
