### ISSUE TITLE
Scaling of kernel 

### ISSUE THREAD

**Issue by PerrineLacour** [koszullab/chromosight#37]
Dear chromosighter,

I have a few questions regarding the _win-size_ option for chromosight detect and quantify.
- I saw that it is set to "auto" by default, does this mean that the kernel size is scaled all the time or is the default size of the kernel used no matter the bin size?
- I ran some analysis with 5kb-binned data, and now want to do the same with higher resolution data (1kb-binned). In case I need to set the scaling factor myself, I would need to set the win-size option to _default size of kernel * 5_ to correct for the difference, is that correct?

Best regards,

**Comment by cmdoret** [comment]
Hi @PerrineLacour,

* The default kernel size is used no matter the bin size, if you want you can use `--win-size` to rescale it to a desired size
* In theory yes, but in my experience it is not that important. Scaling up x2 should be sufficient.

If you want you can also compare the rescaled kernel visually to loops on your map. To view what the rescaled kernel would look like, you could write this in a python console:

```python
import chromosight.kernels as ck
import chromosight.utils.preprocessing as cup
import matplotlib.pyplot as plt

RESIZE_FACTOR = 5

plt.imshow(cup.resize_kernel(ck.loops['kernels'][0], factor=RESIZE_FACTOR))
plt.show()
```

Cyril

**Comment by PerrineLacour** [comment]
Thank you a lot for your answer!

Best,
