### ISSUE TITLE
run chromosight with --inter option on each interchromosome matrix separately

### ISSUE THREAD

**Issue by jazberna1** [koszullab/chromosight#38]
Hello,

I had a go with chromosight 1.4.0 enabling the --inter option. Unfortunatelly I exceeded my RAM limit which is 400GB.

I was wondering if there is a way to analyse each individual interchromosome matrix separatelly and so try to fit in memory.

My datatset (the .cool file) comes from a HiC experiment done in human (GRCh38) and this is how I run chromosight:

```
/mnt/lustre/scratch/SOFTWARE/miniconda3/bin/chromosight \
detect \
--threads=4 \
--inter \
/mnt/lustre/scratch/results.test/matrix/test.matrix.cool \
loops_all

```
Any advise will be much appreciated.

Regards
Jorge

**Comment by cmdoret** [comment]
Hi @jazberna1,

Chromosight already loads only 1 sub matrix (per process) at a any time. So if you have 4 threads, you will have 4 inter/intra-chromosome matrix loaded in RAM at a given time. They are removed from memory as soon as they are processed.

If you want to reduce RAM usage, you can therefore use `--threads=1`, or use a lower resolution matrix. The latter should drastically reduce RAM usage (e.g. going from 10kb to 20kb). Higher coverage matrices also take more RAM.

For now, this is all we can do to reduce RAM usage. The only way to overcome this would be to tile chromosomal matrices and load tile by tile, but we have not yet found the time to implement this.

Cyril

**Comment by jazberna1** [comment]
Hi Cyril,

Thanks so much for replying so fast. I'll try both suggestions --threads=1 and/or lower resolution.

Regards
Jorge
