### ISSUE TITLE
Input to simulated data

### ISSUE THREAD

**Issue by gdolsten** [koszullab/chromosight#42]
Hi, which inputs are we supposed to give to the simulated data?

Particularly in this part of the file: 

```
# Path to positions of borders in the experimental matrix (in bins,
# relative to chromosome start)
borders_pos = np.loadtxt(sys.argv[3])

```

**Comment by cmdoret** [comment]
Hi @gabedolpten,

If you are referring to this script: https://github.com/koszullab/chromosight_analyses_scripts/blob/master/python_codes/chromo_simul.py

You need to give a text file containing a single column of numbers. Each value is the coordinate of a border on the diagonal in the chromosome you are using. Coordinates are expressed in bins relative to chromosome start and are 0-based.

Overall, the inputs of the script are:
* the Hi-C contacts in cool format
* The name of the chromosome to use for training
* The borders coordinates in that chromosome, relative to the chromosome start, in bins.

So let's pretend you have a cool file of the human genome, and will be using chromosome 10. you would do:

`python chromo_simul.py human.cool chr10 borders.txt`

where borders.txt would contain e.g.:

```
10
131
242
...
```

**Comment by gdolsten** [comment]
cmdoret, Do you have the file for the borders/loops that were used for the mitotic S cerevisaie that were used for simulation in the paper? I am trying to benchmark different methods and I would like to use the same benchmarking method you used

**Comment by cmdoret** [comment]
Hi @gabedolpten,

Sorry for the delay, we figured there was a bug in the `chromo_simul.py` script. I previously made a change to make it faster and introduced a bug which caused different results. It is now fixed, so you should use the latest version.

I uploaded the inputs we used for the simulations on the zenodo entry: https://zenodo.org/record/3742094
The 2 files are in simulation_inputs.tar.gz

Best

**Comment by cmdoret** [comment]
I'll close the issue for now, but feel free to reopen if you have additional questions.
