### ISSUE TITLE
Questions about resolution in loop json file

### ISSUE THREAD

**Issue by Linhua-Sun** [koszullab/chromosight#48]
Hi: I found chromosight detect loops quite well in my Hi-C datasets. I found `resolution` in loops.json and loops_small.json are both defined as 2000. **I am wondering whether I should adjust the value if I used 5-kb or 10-kb resolution cooler files?**

Another question: I found `artificial_template_loops_type1.txt` is just like a pileup heatmap, each pixel has specific value.  I wonder if these values in the matrix will affect the results of loop calling by the default options? Do we need to refine these values? 
I also tried to use the --click option from generate-config in order to manually build the kernel by double-clicking on relevant regions in a Hi-C matrix. But it is quite consuming. So failed.
Thanks!

**Comment by cmdoret** [comment]
Hello,

The default kernels is robust to changes in resolution (i.e. works very well with 10kb matrices), so you don't need to resize it.
We provide a `--win-size` option, in case you want to try adjusting kernel size. e.g. the "loops" kernel has a size of 17x17 by default, to 2x larger you would give `--win-size 35` (it has to be an odd number). But having such a large kernel just gives worse results usually.

These heatmaps are the actual kernels used for detection. You can edit the kernel files generated by `generate-config` however you like to reflect the patterns you are looking for, you could even generate the heatmap with custom scripts and save it into the file. The `--click` option just provides an automatic way to do it and is indeed very memory intensive, there is currently no solution to that.

**Comment by Linhua-Sun** [comment]
Thank you very much for your reply, which solved my question very well!
