### ISSUE TITLE
Chromosight for single-cell Hi-C 

### ISSUE THREAD

**Issue by HongguiWu1** [koszullab/chromosight#49]
(python37) [wuhg@mgt module]$ chromosight detect --pattern hairpins --min-dist 50000 --max-dist 2000000 SC_035.mcool::/resolutions/10000  SC_035_hairpins

pearson set to 0.1 based on config file.
min_separation set to 5000 based on config file.
max_perc_undetected set to 75.0 based on config file.
max_perc_zero set to 10.0 based on config file.
Whole genome matrix balanced
Found 12393 / 272566 detectable bins
Preprocessing sub-matrices...
 [====================] 100.0% Y-Y
Sub matrices extracted
Detecting patterns...
 [--------------------] 0.0% Kernel: 0, Iteration: 0
 [====================] 100.0% Kernel: 0, Iteration: 0
Minimum pattern separation is : 1
Traceback (most recent call last):
  File "/share/home/wuhg/.local/bin/chromosight", line 8, in <module>
    sys.exit(main())
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/chromosight/cli/chromosight.py", line 959, in main
    cmd_detect(args)
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/chromosight/cli/chromosight.py", line 802, in cmd_detect
    pval_mask = np.isnan(all_coords.pvalue)
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 1936, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/pandas/core/arraylike.py", line 358, in array_ufunc
    result = getattr(ufunc, method)(*inputs, **kwargs)
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by cmdoret** [comment]
Hello @HongguiWu1 

It seems there is an isssue with your input file. Since you are working on single-cell Hi-C, I wonder whether the structure of the mcool file may be different. Could you show me the output of the following commands on your file:

`cooler tree SC_035.mcool`

`cooler dump -t pixels SC_035.mcool | head 10`

**Comment by HongguiWu1** [comment]
(base) [wuhg@mgt module]$ cooler tree SC_035.mcool
/
 └── resolutions
     ├── 1000
     │   ├── bins
     │   │   ├── chrom (2725549,) int32
     │   │   ├── end (2725549,) int32
     │   │   └── start (2725549,) int32
     │   ├── chroms
     │   │   ├── length (22,) int32
     │   │   └── name (22,) |S32
     │   ├── indexes
     │   │   ├── bin1_offset (2725550,) int64
     │   │   └── chrom_offset (23,) int64
     │   └── pixels
     │       ├── bin1_id (1314109,) int64
     │       ├── bin2_id (1314109,) int64
     │       └── count (1314109,) int32
     ├── 10000
     │   ├── bins
     │   │   ├── chrom (272566,) int32
     │   │   ├── end (272566,) int32
     │   │   ├── start (272566,) int32
     │   │   └── weight (272566,) float64
     │   ├── chroms
     │   │   ├── length (22,) int32
     │   │   └── name (22,) |S32
     │   ├── indexes
     │   │   ├── bin1_offset (272567,) int64
     │   │   └── chrom_offset (23,) int64
     │   └── pixels
     │       ├── bin1_id (1206451,) int64
     │       ├── bin2_id (1206451,) int64
     │       └── count (1206451,) int32
     ├── 100000
     │   ├── bins
     │   │   ├── chrom (27269,) int32
     │   │   ├── end (27269,) int32
     │   │   └── start (27269,) int32
     │   ├── chroms
     │   │   ├── length (22,) int32
     │   │   └── name (22,) |S32
     │   ├── indexes
     │   │   ├── bin1_offset (27270,) int64
     │   │   └── chrom_offset (23,) int64
     │   └── pixels
     │       ├── bin1_id (736986,) int64
     │       ├── bin2_id (736986,) int64
     │       └── count (736986,) int32
     ├── 1000000
     │   ├── bins
     │   │   ├── chrom (2738,) int32
     │   │   ├── end (2738,) int32
     │   │   └── start (2738,) int32
     │   ├── chroms
     │   │   ├── length (22,) int32
     │   │   └── name (22,) |S32
     │   ├── indexes
     │   │   ├── bin1_offset (2739,) int64
     │   │   └── chrom_offset (23,) int64
     │   └── pixels
     │       ├── bin1_id (327379,) int64
     │       ├── bin2_id (327379,) int64
     │       └── count (327379,) int32
     ├── 25000
     │   ├── bins
     │   │   ├── chrom (109033,) int32
     │   │   ├── end (109033,) int32
     │   │   ├── start (109033,) int32
     │   │   └── weight (109033,) float64
     │   ├── chroms
     │   │   ├── length (22,) int32
     │   │   └── name (22,) |S32
     │   ├── indexes
     │   │   ├── bin1_offset (109034,) int64
     │   │   └── chrom_offset (23,) int64
     │   └── pixels
     │       ├── bin1_id (1041886,) int64
     │       ├── bin2_id (1041886,) int64
     │       └── count (1041886,) int32
     ├── 250000
     │   ├── bins
     │   │   ├── chrom (10912,) int32
     │   │   ├── end (10912,) int32
     │   │   └── start (10912,) int32
     │   ├── chroms
     │   │   ├── length (22,) int32
     │   │   └── name (22,) |S32
     │   ├── indexes
     │   │   ├── bin1_offset (10913,) int64
     │   │   └── chrom_offset (23,) int64
     │   └── pixels
     │       ├── bin1_id (567967,) int64
     │       ├── bin2_id (567967,) int64
     │       └── count (567967,) int32
     ├── 2500000
     │   ├── bins
     │   │   ├── chrom (1101,) int32
     │   │   ├── end (1101,) int32
     │   │   └── start (1101,) int32
     │   ├── chroms
     │   │   ├── length (22,) int32
     │   │   └── name (22,) |S32
     │   ├── indexes
     │   │   ├── bin1_offset (1102,) int64
     │   │   └── chrom_offset (23,) int64
     │   └── pixels
     │       ├── bin1_id (175226,) int64
     │       ├── bin2_id (175226,) int64
     │       └── count (175226,) int32
     ├── 5000
     │   ├── bins
     │   │   ├── chrom (545118,) int32
     │   │   ├── end (545118,) int32
     │   │   └── start (545118,) int32
     │   ├── chroms
     │   │   ├── length (22,) int32
     │   │   └── name (22,) |S32
     │   ├── indexes
     │   │   ├── bin1_offset (545119,) int64
     │   │   └── chrom_offset (23,) int64
     │   └── pixels
     │       ├── bin1_id (1273134,) int64
     │       ├── bin2_id (1273134,) int64
     │       └── count (1273134,) int32
     ├── 50000
     │   ├── bins
     │   │   ├── chrom (54521,) int32
     │   │   ├── end (54521,) int32
     │   │   └── start (54521,) int32
     │   ├── chroms
     │   │   ├── length (22,) int32
     │   │   └── name (22,) |S32
     │   ├── indexes
     │   │   ├── bin1_offset (54522,) int64
     │   │   └── chrom_offset (23,) int64
     │   └── pixels
     │       ├── bin1_id (884664,) int64
     │       ├── bin2_id (884664,) int64
     │       └── count (884664,) int32
     └── 500000
         ├── bins
         │   ├── chrom (5463,) int32
         │   ├── end (5463,) int32
         │   └── start (5463,) int32
         ├── chroms
         │   ├── length (22,) int32
         │   └── name (22,) |S32
         ├── indexes
         │   ├── bin1_offset (5464,) int64
         │   └── chrom_offset (23,) int64
         └── pixels
             ├── bin1_id (448441,) int64
             ├── bin2_id (448441,) int64
             └── count (448441,) int32
when I run cooler dump -t pixels SC_035.mcool | head 10, it ended with an error, please see following.

(python37) [wuhg@mgt module]$ cooler dump -t pixels SC_035.mcool | head 10
head: cannot open ‘10’ for reading: No such file or directory
Traceback (most recent call last):
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/cooler/api.py", line 95, in _refresh
    _ct = chroms(grp)
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/cooler/api.py", line 448, in chroms
    .append(pd.Index(h5["chroms"].keys()))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/h5py/_hl/group.py", line 288, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'chroms' doesn't exist)"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/home/wuhg/.local/bin/cooler", line 8, in <module>
    sys.exit(cli())
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/cooler/cli/_util.py", line 200, in decorated
    func(*args, **kwargs)
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/cooler/cli/dump.py", line 345, in dump
    c = api.Cooler(cool_uri)
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/cooler/api.py", line 89, in __init__
    self._refresh()
  File "/share/home/wuhg/.local/lib/python3.7/site-packages/cooler/api.py", line 110, in _refresh
    raise KeyError(err_msg)
KeyError: "No cooler found at: SC_035.mcool. Coolers found in ['/resolutions/1000', '/resolutions/5000', '/resolutions/10000', '/resolutions/25000', '/resolutions/50000', '/resolutions/100000', '/resolutions/250000', '/resolutions/500000', '/resolutions/1000000', '/resolutions/2500000']. Use '::' to specify a group path"

**Comment by cmdoret** [comment]
Oh yes my bad, it was a mistake on my part (should have been `cooler dump -t pixels SC_035.mcool::/resolutions/10000 | head -n 10`, but from the output of `cooler tree`, your file looks normal.

Looking at the logs from your chromosight run, it seems you matrix has very low coverage:
`Found 12393 / 272566 detectable bins`
That means only 4.5% of the matrix bins had sufficienf contacts.

You can check the number of contacts in the matrix by running:
`cooler info SC_035.mcool::/resolutions/10000` but I suspect the number of contacts is too low for Chromosight to see anything.
To make sure, it would be good to inspect the map by eye (using `cooler show`) and see what it looks like.

If the map looks mostly empty without discernable structure, you'll need more coverage for this type of analysis.

**Comment by HongguiWu1** [comment]
I run the command, and the output is shown following. Yes, you are right, since it's single cell data, for this cell, we have total 1, 206, 451 contacts, which is really good for single cell. But obviously, it's not comparable with bulk data. We did see some interesting hairpin-like structures with eys inspection, that's why we want to use Chromosight to quantify and validate to avoid artificial error. Would you please provide some suggestions which make it's feasible to use Chromosight for single-cell datasets?

cooler dump -t pixels SC_035.mcool::/resolutions/10000 | head -n 10

300	304	1
300	307	1
300	308	1
300	632	1
300	207819	1
301	301	1
301	303	1
301	310	1
301	146748	1
302	2658	1

**Comment by cmdoret** [comment]
1M contacts for a mammal map is indeed too low for Chromosight to work, unfortunately.

I have not tried it, maybe you could try using something like [SRHi-C](https://www.frontiersin.org/articles/10.3389/fgene.2020.00353/full) to artificially increase your resolution, then regenerate a cool file with the enhanced data and feed it to Chromosight.

Good luck with your analyses !

**Comment by HongguiWu1** [comment]
Thank you for your detailed explanation and guidance. I will try your suggestion and may use some imputation algorithm to increase coverage. Thanks with full-hearted.

All the best!

**Comment by HongguiWu1** [comment]
Hi @cmdoret, I run Chromosight on our bulk Hi-C dataset to call hairpin-like structures. But I found that for many top score hit  regions are located at mask region. Do you have any suggestion for that result.

Best,
Honggui

**Comment by cmdoret** [comment]
Hi @HongguiWu1,

What do you call mask regions ? Are you talking about white bins in the Hi-C map ?
If so, you could try reducing `--perc-undetected` or even setting it to 0. Note this will only work if those bins contain "NaN" values, which is the case if they were erased by the balancing procedure due to low coverage. If you "masked" them by hand and set them to 0, then you may want to decrease `--perc-zero` instead.

Cheers,
Cyril
