### ISSUE TITLE
Point and click mode

### ISSUE THREAD

**Issue by ysora** [koszullab/chromosight#50]
Could you upload basic usage of 'point and click' mode?
I used config-generate function, but got an error as below:

**sora@server:my/path/to/chromosight$ chromosight generate-config --threads 10 --click myfile.mcool::resolutions/5000 my_prefix**
Matrix already balanced, reusing weights
Found 500267 / 545114 detectable bins
Preprocessing sub-matrices...
 [====================] 100.0% chrY-chrY
Sub matrices extracted

Traceback (most recent call last):
  File "/home/sora/.local/bin/chromosight", line 8, in <module>
    sys.exit(main())
  File "/home/sora/.local/lib/python3.8/site-packages/chromosight/cli/chromosight.py", line 961, in main
    cmd_generate_config(args)
  File "/home/sora/.local/lib/python3.8/site-packages/chromosight/cli/chromosight.py", line 536, in cmd_generate_config
    windows = click_finder(processed_mat, half_w=int((win_size - 1) / 2))
  File "/home/sora/.local/lib/python3.8/site-packages/chromosight/utils/plotting.py", line 139, in click_finder
    plt.imshow(mat.toarray(), cmap="afmhot_r", vmax=np.percentile(mat.data, 95))
  File "/mnt/data0/apps/anaconda/Anaconda2-5.2/envs/py38/lib/python3.8/site-packages/scipy/sparse/compressed.py", line 1029, in toarray
    out = self._process_toarray_args(order, out)
  File "/mnt/data0/apps/anaconda/Anaconda2-5.2/envs/py38/lib/python3.8/site-packages/scipy/sparse/base.py", line 1185, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
MemoryError: Unable to allocate 2.16 TiB for an array with shape (545114, 545114) and data type float64

I guess there is an memory issue. Could you suggest any solution for this??

**Comment by cmdoret** [comment]
Hi,

Indeed, this point and click mode is pretty memory heavy with large genomes, but your usage is correct.
One of the advice would be to use a lower resolution to reduce the size of the matrix, but I realize this is often not desirable.

I have just released a patch (v0.6.0) with an additional `--chroms` option which allows you to specify a list of chromosomes. When you use it in point and click mode, it will load each submatrix sequentially, and use much less memory. If you are also interested in interchromosomal contacts, you can also add the `--inter` flag. Example usage would be:

```sh
chromosight generate-config --click sample.cool --chroms chrom3,chrom5,chrom20 my_config
```

I'm happy to take any feedback or suggestion :)

Another solution would be to use an agglomerated matrix you generated with another method (e.g. using something like [coolpup.py](https://github.com/open2c/coolpuppy) or custom scripts.  You could even use a theoretical pattern, here is an example snippet to generate a basic stripe pattern:

```python
import numpy as np
pattern_mat = np.zeros((17, 17))
pattern_mat[8, :] = 1.0
np.savetxt('pattern_stripe.txt', pattern_mat)
```

Then you could edit the "kernels" entry of your json config file to match the file name:
```
    "kernels": [
        "pattern_stripe.txt"
    ],
```

If you find a kernel that works well for your pattern, we would be happy to add it to the list of preconfigured kernels.

**Comment by ysora** [comment]
Thanks, chromosome selection took also long time but finally worked! 
Also, thank you for suggesting another solution.

**Comment by cmdoret** [comment]
Glad to know it worked ! 

In case that can be helpful, I have added two experimental kernel configurations `stripes_left` and `stripes_right`.
You should be able to use them by updating chromosight to v1.6.1 via pip.

Cheers,

**Comment by ysora** [comment]
Great, thanks.
I will try and let you know the result.

**Comment by ysora** [comment]
I tested it and found it works well. I have one question. What does the location of each dot mean? Is it marking the end of stripe? 
Thanks.

**Comment by cmdoret** [comment]
With stripes, the dots themselves do not have much meaning unfortunately. A dot represents a region of the matrix that looks especially like a stripe. Most of the time, there will be many dots aligned on a single stripe.

After detecting `stripes_left`, here is one way you could extract stripes from dots:

```python
import pandas as pd
from chromosight.utils.detection import remove_neighbours
df = pd.read_csv('stripes_left.tsv', sep='\t')
# stripes_left positions are defined by bin1, but bin2 is arbitrary.
# We set bin2 to bin1 so that stripes dots are on the diagonal at the base of the stripe
df[ 'bin2'] = df['bin1'].copy()
# Filter out dots too close to another dot with a higher score
keep_mask = remove_neighbours(df, win_size=4)
# In the filtered dataframe, chrom1, start1, end1 and bin1 give coordinates of the left stripes
df = df.loc[keep_mask, ]
```

With `stripes_left`, points on the same stripe are aligned on the  `bin1` axis.
With `stripes_right`, they're aligned on the `bin2` axis. So for `right_stripes`, coordinates of axis 2 are relevant and bin1 should be set to bin2 values.

**Comment by ysora** [comment]
Thank you for your kind explanation!

**Comment by cmdoret** [comment]
I'll be closing this for now but feel free to reopen if needed
