### ISSUE TITLE
Different number of patterns for the same Hi-C matrix

### ISSUE THREAD

**Issue by magnitov** [koszullab/chromosight#51]
Hi!

I run into the following issue. When I execute Chromosight v1.4.1, I get slightly different number of loops (<100 differences) each time I run the calculations for the exact same Hi-C matrix. I wonder why this might happen and whether there is a way to make it robust in detection (is there a seed somewhere?).

Best,
Mikhail

**Comment by cmdoret** [comment]
Hi @magnitov 

Unfortunately, I could not reproduce your issue. I got consistent number of loops on the yeast, mouse and human datasets I tried (chromosight v1.6.0). That was just running `chromosight detect -t6 sample.cool output`.

Could you specify what command you used, or even better, if you have an example of a public dataset (e.g. from https://data.4dnucleome.org/) where you encountered this problem.

If it happens on your own data and you are comfortable with sharing it, you could send me the cool file by email (cyril.matthey-doret@pasteur.fr) and I will investigate where the randomness comes from.

**Comment by magnitov** [comment]
Hi @cmdoret,

I realized that for some reason I never came back to this issue. So, after a bit of investigation, I found out that there was a bug at the step before Chromosight, so those were actually not exactly the same Hi-C matrices. I believe this issue can be then closed, since the software is totally OK.

Best,
Mikhail

**Comment by cmdoret** [comment]
Thanks a lot for taking the time to come back to the issue ! Great news :)
