### ISSUE TITLE
How to evaluate the detected loops?

### ISSUE THREAD

**Issue by frankchen121212** [koszullab/chromosight#52]
Hello, thank you for the nice work~

I'm interested in how you evaluate your detected loops? In the paper, you mentioned that it was calculated through p-value

However, have you compared your result with the ground truth annotation?

For example, you detected a loop, let's say "loop No.1", so, how would you classify that your detected "loop No.1" into a True Positive detection? From my perspective, I think the detected "loop No.1" should be somehow "close" to the ground truth loop "Ground Truth loop No.1" before it can be classified into a correct detection.

Hope that you could help me thank you!

**Comment by axelcournac** [comment]
Hi Siyuan, thanks for your interest in Chromosight. The detections are established by calculating the correlation (Pearson coefficient) with a generic loop pattern.  
The patterns are said to be positive detections if the computed coefficient is above a threshold (by default, we put the value 0.4 but you can change it with the option -pearson). 
Then the pvalue are computed with the function corr_to_pval: given a list of Pearson correlation coefficient, the function converts them to two-sided log10 p-values. The p-values are computed via the fisher transformation described on: https://w.wiki/Ksu

link to the function: [corr_to_pval](https://github.com/koszullab/chromosight/blob/bf266ecc286878386726e525ca01d82be730a0b7/chromosight/utils/stats.py#:~:text=def-,corr_to_pval,-(corr%2C%20n%2C%20rho0))
Hope it helps.

**Comment by frankchen121212** [comment]
Thank you for the prompt response! 

To be more specific, does that mean that the Pearson coefficient is calculated by comparing the output "prefix.tsv" with the ground truth file? 

Thank you again for your advice!

**Comment by axelcournac** [comment]
The Pearson coefficient is computed between patches of your contact data (for example patches of 17x17 along your normalized contact map) and a generic pattern for example a loop pattern 17x17 (that we created from experimental datasets or can be generated with a [gaussian 2D kernel](https://www.google.com/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F29731726%2Fhow-to-calculate-a-gaussian-kernel-matrix-efficiently-in-numpy&psig=AOvVaw3xroGF5NEIM8c_U4iVn545&ust=1627379138249000&source=images&cd=vfe&ved=0CAoQjRxqFwoTCMj6n_a5gPICFQAAAAAdAAAAABAX))

Files for generic patterns of loops, borders, hairpins can be found here: 
https://github.com/koszullab/chromosight/tree/master/chromosight/kernels
Best,

**Comment by frankchen121212** [comment]
Thank you very much for your advice!

I will close this issue.
