### ISSUE TITLE
Different number of loops on GM12878 Hi-C map

### ISSUE THREAD

**Issue by zhang-jiankun** [koszullab/chromosight#53]
Hi,

I read the Chromosight paper, and I have a question about the loop calling on GM12878 Hi-C data. Below were the two statements about these results from the paper.

> **Presentation and benchmark of Chromosight.** 
For instance, Chromosight found 85% of the loops detected by Cooltools, the software with the highest precision in our benchmark, while overall identifying a much larger number of loops (37,955 vs. 6264, respectively) (Supplementary Fig. 3c).

> **Exploration of various genomes and patterns.**  
With default parameters, Chromosight identified 18,839 loops (compared to !10,000 detected in ref. 6) whose anchors fall mostly (~ 58%, P < 10!16) into loci enriched in cohesin subunit Rad21 (Fig. 3b).

If I understand correctly, you applied Chromosight to call loops on the same dataset in Rao et al., _Cell_ 2014. So, I was wondering why Chromosight yielded different results (37955 vs. 18839). I would be grateful if you could clarify this point.

Thank you so much.

Jinakun

**Comment by cmdoret** [comment]
Hi @zhang-jiankun,

Thanks for your interest. I now realize the text is confusing. Both figures are obtained with default parameters, but 18,839 was obtained on the recent Arima dataset from Ghurye et al. (ref 36 in the sentence) whereas 37,955 was obtained on the Rao et al. dataset.

The reason for this large difference is that the Rao et al. dataset is 10 times (!) more highly covered (but also more noisy) than the recent Arima dataset. Looking back, it would have made more sense to use exclusively Rao et al. for all comparisons. Logically, we should have used the same figure (37,955) in the second sentence. Thanks for raising this issue !

Best,
Cyril

**Comment by cmdoret** [comment]
Regarding the figures (37,955 vs 18,839 detected loops), I now realize the text is quite confusing. Both are obtained with default parameters, but 18,839 was obtained on the recent Arima dataset from Ghurye et al. (ref 36) whereas 37,955 was obtained on the Rao et al. dataset.

The reason for this large difference is that the Rao et al. dataset is 10 times (!) more highly covered. Looking back, it would have made more sense to use exclusively Rao et al. for all comparisons.

**Comment by zhang-jiankun** [comment]
Hi Cyril,

Thanks for clarifying that.

Best,
Jiankun
