### ISSUE TITLE
chromosight detects hairpin, the numer is too large

### ISSUE THREAD

**Issue by HongguiWu1** [koszullab/chromosight#54]
Hi 
I used chromosight to detect hairpins in our dataset, but I got a large number of hairpins, that's not normal, here is my report. Do you have any suggestions, is there any parameters that I set wrong?

detect --threads 10 --pattern hairpins --min-dist 50000 --max-dist 2000000 gm12878_microc.mcool::resolutions/10000 /gshare/xielab/wuhg/published/Micro-C_hairpins
pearson set to 0.1 based on config file.
min_separation set to 5000 based on config file.
max_perc_undetected set to 75.0 based on config file.
max_perc_zero set to 10.0 based on config file.
Matrix already balanced, reusing weights
Found 261150 / 308839 detectable bins
Preprocessing sub-matrices...
 [====================] 100.0% chrY-chrY
Sub matrices extracted
Detecting patterns...
 [--------------------] 0.0% Kernel: 0, Iteration: 0
 [====================] 100.0% Kernel: 0, Iteration: 0
Minimum pattern separation is : 1
186221 patterns detected
Saving patterns in /gshare/xielab/wuhg/published/Micro-C_hairpins.tsv
Saving patterns in /gshare/xielab/wuhg/published/Micro-C_hairpins.json
Saving pileup plots in /gshare/xielab/wuhg/published/Micro-C_hairpins.pdf

**Comment by axelcournac** [comment]
Hi,
Maybe you can increase the pearson coefficient a bit, which is the threshold at which a pattern is considered as hairpin: 
--pearson=0.2 or 0.3
This type of pattern is usually on the primary diagonal, so I would decrease the max distance: 
--max-dist 200000
Best
