### ISSUE TITLE
Bus error in chromosight quantify

### ISSUE THREAD

**Issue by mannekim** [koszullab/chromosight#56]
Hi, i get this error when I try to run chromosight quantify from using the output from chromosome detect:

![image](https://user-images.githubusercontent.com/44848241/166730901-095833a5-14ee-482e-8bc7-3879320901bc.png)

How can I fix this?

**Comment by mannekim** [comment]
After googling, it may be because of not enough space. I'll try running it again with bigger space

**Comment by cmdoret** [comment]
Hi @mannekim, did that solve the problem ?
