### ISSUE TITLE
Is there a way to use multiresolution .mcool files directly?

### ISSUE THREAD

**Issue by Elphege-Nora** [koszullab/chromosight#58]
Thanks for a great software!

For chromosight quantify , is there a way to use multiresolution .mcool files directly (specifying the desired resolution)?
Or does chromosight only take uni-resolution .cool files as input?

**Comment by axelcournac** [comment]
Hi, thanks for the feedback. It is possible to use mcool files directly. Here an example: 
 ```
chromosight quantify \
    --threads=10 \
    --pattern=loops_small \
    loop_positions.tsv \
    sample.mcool::/resolutions/4000 \
    sample_output
```
 Best
