### ISSUE TITLE
Where do these kernels come from?

### ISSUE THREAD

**Issue by zhyanlin** [koszullab/chromosight#60]
Hello,

Thanks for developing such a great tool! When I use chromosight, I have a question in mind. Chromosight uses a loop kernel to detect loops from a Hi-C contact map. But where does this loop kernel come from? Does the loop kernel come from a Hi-C data set or somewhere else?

**Comment by axelcournac** [comment]
Hello,
Thanks for the feedback. The kernel loop were initially created with Hi-C data from yeast S. Cerevisiae at 2 kb resolution but it can apply to various different types of data. There are 2 different loop kernels currently implemented that you can choose with the kernel option: loops and loops_small that have a different size. You can make your own kernel (for example a simple theoretical 2D gaussian filter) by creating your own json file:
[https://chromosight.readthedocs.io/en/latest/TUTORIAL.html#generating-custom-patterns](https://chromosight.readthedocs.io/en/latest/TUTORIAL.html#generating-custom-patterns)

**Comment by zhyanlin** [comment]
Thank you!

**Comment by zhyanlin** [comment]
> The kernel loop were initially created with Hi-C data from yeast S. Cerevisiae at 2 kb resolution

I realized that I still didn't understand how to get the loop kernel. 
I assume that loops in the yeast S. Cerevisiae contact map are unknown until applying your kernel to detect them. Did you annotate loops in yeast with another tool or use experiments such as ChIA-PET to get loops to define kernels?

**Comment by axelcournac** [comment]
We extracted by eye about twenty loops that were very clear in S. Cerevisiae and performed the pileup. This already gave a satisfactory kernel, which could also be corrected by hand if there was still some noise or to make it symmetrical. We did not use an alternative technique like ChIA-PET for the first annotation.

**Comment by zhyanlin** [comment]
Thank you for your answer!
