### ISSUE TITLE
Loop score calculation

### ISSUE THREAD

**Issue by WanyingX** [koszullab/chromosight#62]
Hi, 

I am wondering how you calculate the loop score?

thanks

**Comment by axelcournac** [comment]
Hi, 
The loop score is computed by calculating the Pearson Coefficient of a submatrice involving a certain region in the contact map (detrended for the genomic distance effect) with a generic pattern for example a loop pattern. Such generic patterns are given in Fig1.a of our paper (in blue white red). The loop score can be between -1 and 1.
More precise information on the computation can be found in a similar issue: 
https://github.com/koszullab/chromosight/issues/57

**Comment by WanyingX** [comment]
Thanks! I see. For example, If I have two condtion and suppose to detect the difference between two conditions. 
So, firstly, I need to use detect-mode to identify loops from both of them. 
And then, i need to merge all of them and run quantify-mode to get loop score for each pixel. Is this correct?

One more question, so for the loop score measurement, you consider the local similiarity only or you consider the global background to calculate your loop strength(score).

**Comment by axelcournac** [comment]
Yes to compare two conditions, you can also use this script :
https://github.com/koszullab/chromosight_analyses_scripts/blob/master/bash_scripts/detect_loops_venn2.sh
We consider the local similarity taking into account the global background: we detrend by the genomic distance effect for each condition as presented in Fig1.b of the paper.

**Comment by NesmaAhmed** [comment]
How can I run score_loops.py, I am trying this code but I got an error "file not found"
python3 score_loops.py "$prediction.txt" "$target.txt"  -- area=3  --size=289
