### ISSUE TITLE
Pattern = TAD?

### ISSUE THREAD

**Issue by aminakur** [koszullab/chromosight#63]
Thank you for creating Chromosight, it is such a great tool. Are there any plans to create a forth pattern option for detection, which will be a TAD (a classic triangle-shaped domain)? Or, how easy it would be for a user to create it as a custom pattern?

I think this could be a cool thing to add since TADs have been shown to be not continuous along chromosomes of some species. In these cases, simply calling boundaries and calling the space between two boundaries a "TAD" doesn't always have biological meaning.

**Comment by cmdoret** [comment]
Hi @MyBiscuit,
There is a general tutorial on how to add pattern here:
https://chromosight.readthedocs.io/en/latest/TUTORIAL.html#generating-custom-patterns

In your case, I'm not sure if I understand what the pattern is, but you could generate the config as explained in the tutorial, then replace the txt file with with your own custom kernel matrix. A kernel matrix is simply a plain-text space separated file (see e.g. [this one](https://github.com/koszullab/chromosight/blob/master/chromosight/kernels/artificial_template_borders_type1.txt)).

You could make the matrix of your pattern in python with numpy, and save it using [numpy.savetxt](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html). Then you just need to make sure your pattern config JSON file points to your newly generated kernel txt file.
